Get-AppxPackage *bingnews*    | Remove-AppxPackage
Get-AppxPackage *bingweather* | Remove-AppxPackage
Get-AppxPackage *bingfinance* | Remove-AppxPackage
Get-AppxPackage *bingsports*  | Remove-AppxPackage
Get-AppxPackage *xboxapp*     | Remove-AppxPackage
Get-AppxPackage *onenote*     | Remove-AppxPackage
Get-AppxPackage *officehub*   | Remove-AppxPackage
Get-AppxPackage *skypeapp*    | Remove-AppxPackage
Get-AppxPackage *sway*        | Remove-AppxPackage
Get-AppxPackage *Twitter*     | Remove-AppxPackage